name: Module 2 - Unit Tests

on:
  workflow_run:
    workflows: ["Module 1 - Linting"]
    types: [completed]

jobs:
  unit-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn redis fakeredis pytest pytest-cov httpx

      - name: Run Tests with Coverage
        # This generates a .xml report for the artifact
        run: |
          pytest --cov=api --cov-report=xml tests/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 1
